### ISSUE TITLE
Insert into - dont´ save data

### ISSUE THREAD

**Issue by baltazaroliveira** [lovasoa/sql.js#20]
What i am doing wrong? (Using on Mobile App).

// == SQL == //

    var xhr = new XMLHttpRequest();
    xhr.open('GET', 'db/Catalogos.db', true); //async
    xhr.responseType = 'arraybuffer';

    //

    xhr.onload = function (e) {

        var uInt8Array = new Uint8Array(this.response);
        var db = new SQL.Database(uInt8Array);

        sqlstr = "INSERT INTO hl_NumeracaoAnoUtlzs VALUES, ('1','2','3');";

        console.info("1");
        db.run(sqlstr);
        /*
        console.info("2");
        db.exec(sqlstr);
        */

        // fecha a ligação á BD
        db.close();
    };
    xhr.send();

**Comment by lovasoa** [comment]
Can you give a bit more details? What error are you getting?

**Comment by baltazaroliveira** [comment]
Using with Ionic on prepopulated SQLITE 3 Db. The DB is inside my App. I can do selects without problem.

I don´t have errors but if i execute the same insert 2 times i get a error because of indices.

![image](https://cloud.githubusercontent.com/assets/953742/5846176/a5e02522-a1b9-11e4-9794-a010786c8c6e.png)

![image](https://cloud.githubusercontent.com/assets/953742/5846157/7dc17db6-a1b9-11e4-8e72-068ccf6d0575.png)

When i go check the table, the data is not saved. Do i have to save the db? If yes it is possible doing with "normal" javascript?

I have permission to write in file.

Thanks

**Comment by lovasoa** [comment]
With sql.js, the whole database lies in memory.
If you want to transparently reflect your changes to the database, and don't worry about having your app depending on a compiled module, you can use  node-sqlite3: https://github.com/mapbox/node-sqlite3

If you want to use sql.js, you will have to manually export the database, with db.export().

**Comment by lovasoa** [comment]
There is a section in the README about writing the database to the disk.

**Comment by baltazaroliveira** [comment]
Sorry the newbie question. Node.Js works on mobile devices?

**Comment by baltazaroliveira** [comment]
Using this code 

![image](https://cloud.githubusercontent.com/assets/953742/5853170/7e08c2a2-a218-11e4-8f57-1d8edaf02de7.png)

I get this error

![image](https://cloud.githubusercontent.com/assets/953742/5853174/878212d4-a218-11e4-8ec7-ce4d9a827676.png)

I am missing something?

**Comment by baltazaroliveira** [comment]
Have a answer?

**Comment by lovasoa** [comment]
No, node.js is not intended to work on mobile devices. You should read the documentation of whatever framework you used to reate your mobile app in js.

**Comment by baltazaroliveira** [comment]
Ok. Thanks.
