### ISSUE TITLE
Data not returning

### ISSUE THREAD

**Issue by warpdriv** [lovasoa/sql.js#24]
Hi,

I have the below code which for some reason is not returning any data. It finds the sqlite file and loads it find, but the query does not return any data. I have searched multiple sites but have not found an answer. I have also tried this on Flask and IIS with the same results.

Can you please help me? Thank you.

`﻿<html lang='en'>
<head>
    <script src="/static/js/lib/sql.js"></script>
</head>
<body>
    <div id='data'></div>
    <script>
	try
	{
		console.log("we are here");
		var file = "/static/data/results.db3";

		var xhr = new XMLHttpRequest();
		xhr.open('GET', file, true);
		xhr.responseType = 'arraybuffer';

		xhr.onload = function() {
		try{
			var data = new Uint8Array(this.response);
			var db = new SQL.Database(data);
			var contents = db.exec('SELECT value FROM results');

			contents.forEach(function(row) {
			    console.log(row.value);
			});
		}
		catch(err){
			console.log(err.message);
		}
		};
		
		xhr.send();
	}
	catch(err)
	{
		document.getElementById("data").innerHTML = err.message;
	}
    </script>
</body>
</html>`

**Comment by hankinsoft** [comment]
This repository is out of date. Have you tried the one mentioned in the readme? https://github.com/kripken/sql.js
